@echo off
echo SRC_DIR=%SRC_DIR%
echo BUILD_DIR=%BUILD_DIR%
echo INSTALL_PREFIX=%INSTALL_PREFIX%
@rem SET PATH="%ORIGINAL_PATH%;%MSYSTEM_PREFIX%\bin"
SET MESON_CMD=meson
SET MSYS_NO_PATHCONV=1
CD /D "%BUILD_DIR%"
%MESON_CMD% setup "%SRC_DIR%" --vsenv  --prefix "%INSTALL_PREFIX%" %*&&%MESON_CMD% compile -C .&&%MESON_CMD% install -C .
EXIT %ERRORLEVEL%