set(VCPKG_TARGET_ARCHITECTURE arm)
set(VCPKG_CMAKE_SYSTEM_VERSION 10.0.19041.0)
set(VCPKG_CRT_LINKAGE static)
set(VCPKG_LIBRARY_LINKAGE static)

if(PORT MATCHES "^ffmpeg-.+-shared$")
    set(VCPKG_LIBRARY_LINKAGE dynamic)
endif()
