"""Generate the ffmpeg-deps virtual port."""

import json
from pathlib import Path

try:
    import yaml as _yaml
except ImportError:
    import sys
    sys.exit("ERROR: pip install pyyaml required")

REPO_ROOT = Path(__file__).resolve().parents[2]
YAML_DIR = REPO_ROOT / "ffmpeg"
PORTS_DIR = REPO_ROOT / "ports"


def generate_deps_port():
    """Generate the ffmpeg-deps virtual port from base.yaml.

    Scans ALL features in base.yaml, inherits per-feature ``platform``
    expressions, and writes ``ports/ffmpeg-deps/vcpkg.json``.
    """
    base_path = YAML_DIR / "base.yaml"
    with open(base_path, encoding="utf-8") as f:
        base = _yaml.safe_load(f)

    features = base.get("features", {})

    # Scan all version YAMLs for dep_overrides
    alt_override_deps = {}
    for f in sorted(YAML_DIR.glob("*.yaml")):
        if f.stem in ("base", "master"):
            continue
        with open(f, encoding="utf-8") as fh:
            doc = _yaml.safe_load(fh)
        for key, val in doc.get("dep_overrides", {}).items():
            alt_override_deps.setdefault(key, set()).add(val)

    alt_base_deps = {}
    for key in alt_override_deps:
        feat = features.get(key, {})
        base_deps = set()
        for d in _normalise_list(feat.get("depends", [])):
            if isinstance(d, str) and not d.startswith("@"):
                base_deps.add(d)
            elif isinstance(d, dict) and not d.get("name", "").startswith("@"):
                base_deps.add(d["name"])
        alt_base_deps[key] = base_deps

    alternative_dep_names = set()
    for deps in alt_base_deps.values():
        alternative_dep_names.update(deps)
    for deps in alt_override_deps.values():
        alternative_dep_names.update(deps)

    dep_platforms = {}
    for name, info in features.items():
        fp = info.get("platform")
        for item in _normalise_list(info.get("depends", [])):
            dep_name = None
            dep_plat = fp
            if isinstance(item, str):
                if item.startswith("@"):
                    continue
                dep_name = item
            elif isinstance(item, dict):
                n = item.get("name", "")
                if n.startswith("@"):
                    continue
                dep_name = n
                if "platform" in item:
                    dep_plat = item["platform"]
            if dep_name:
                dep_platforms.setdefault(dep_name, set()).add(dep_plat if dep_plat else None)

    for key, override_vals in alt_override_deps.items():
        feat = features.get(key, {})
        fp = feat.get("platform")
        for ov in override_vals:
            dep_platforms.setdefault(ov, set()).add(fp if fp else None)

    def _dep_entry(name, platforms):
        if None in platforms:
            return name
        plist = sorted(p for p in platforms if p)
        if len(plist) == 1:
            return {"name": name, "platform": plist[0]}
        combined = "(" + ") | (".join(plist) + ")"
        return {"name": name, "platform": combined}

    all_entries = []
    feature_entries = {}
    for dep_name in sorted(dep_platforms):
        platforms = dep_platforms[dep_name]
        entry = _dep_entry(dep_name, platforms)
        if dep_name in alternative_dep_names:
            feature_entries[dep_name] = [entry]
        else:
            all_entries.append(entry)

    feat_defs = {}
    if all_entries:
        feat_defs["all"] = {
            "description": "All non-conflicting FFmpeg dependencies",
            "dependencies": all_entries,
        }
    for dep_name in sorted(feature_entries):
        feat_defs[dep_name] = {
            "description": f"External dependency: {dep_name}",
            "dependencies": feature_entries[dep_name],
        }

    port_dir = PORTS_DIR / "ffmpeg-deps"
    port_dir.mkdir(parents=True, exist_ok=True)

    json_data = {
        "name": "ffmpeg-deps",
        "version": "1.0.0",
        "port-version": 0,
        "description": [
            "Auto-generated virtual port — union of all FFmpeg feature dependencies.",
            "Generated by scripts/generate --generate-deps",
        ],
        "dependencies": [],
    }
    if feat_defs:
        json_data["features"] = feat_defs

    (port_dir / "vcpkg.json").write_text(
        json.dumps(json_data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )

    (port_dir / "portfile.cmake").write_text(
        'message(STATUS "[ffmpeg-deps] All dependencies resolved by vcpkg dependency graph")\n'
        '\n'
        'file(COPY "${CMAKE_CURRENT_LIST_DIR}/copyright"\n'
        '     DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")\n'
        '\n'
        'file(INSTALL "${CMAKE_CURRENT_LIST_DIR}/copyright"\n'
        '     DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}"\n'
        '     RENAME copyright)\n',
        encoding="utf-8",
    )

    (port_dir / "copyright").write_text(
        "FFmpeg dependency packages — see individual package copyrights.\n",
        encoding="utf-8",
    )

    print(f"Generated ffmpeg-deps/ with {len(all_entries)} deps in 'all' feature"
          + (f", {len(feature_entries)} conflict features" if feature_entries else ""))


def _normalise_list(raw):
    if isinstance(raw, str):
        return [raw]
    if isinstance(raw, dict):
        return [raw]
    return list(raw) if raw else []
