"""Port file template generation."""

import json
from pathlib import Path


def generate_portfile(version: str, sha512: str, build: dict,
                      patch_names: list[str], port_dir: Path,
                      revision: int = 0, source: dict | None = None):
    """Generate portfile.cmake."""
    base_opts = build.get("base_options", "")
    debug_opts = build.get("debug", {}).get("options", "")

    lines = []
    lines.append(f'set(FFMPEG_VERSION "{version}")')
    lines.append(f"set(FFMPEG_SHA512 {sha512})")
    lines.append(f"set(FFMPEG_PORT_REVISION {revision})")
    if base_opts:
        lines.append(f'set(FFMPEG_BASE_OPTIONS "{base_opts}")')
    if debug_opts:
        lines.append(f'set(FFMPEG_OPTIONS_DEBUG "{debug_opts}")')

    # Emit cmake variable definitions from YAML build.cmake_defines
    cmake_defines = build.get("cmake_defines", {})
    for k, v in cmake_defines.items():
        lines.append(f'set({k} {v})')

    # Emit FFMPEG_REF when ref differs from default n{version}
    source_ref = (source or {}).get("ref", "")
    default_ref = f"n{version}"
    if source_ref and source_ref != default_ref:
        lines.append(f'set(FFMPEG_REF "{source_ref}")')

    lines.append("set(FFMPEG_PATCHES")
    for pn in patch_names:
        lines.append(f'    "${{CMAKE_CURRENT_LIST_DIR}}/patches/{pn}"')
    lines.append(")")
    lines.append('set(CURRENT_PORT_DIR "${CMAKE_CURRENT_LIST_DIR}")')
    lines.append('include("${CMAKE_CURRENT_LIST_DIR}/builder/ffmpeg-portfile.cmake")')

    (port_dir / "portfile.cmake").write_text("\n".join(lines) + "\n", encoding="utf-8")


def generate_vcpkg_json(version: str, feats: dict, feature_deps: dict,
                        feature_refs: dict, host_deps: list, revision: int,
                        merged: dict, port_dir: Path, port_name: str = "ffmpeg",
                        display_ver: str | None = None):
    """Generate vcpkg.json."""
    features = feats["features"]
    defaults = feats.get("defaults", [])
    base_registry = merged.get("features", {})

    feat_defs = {}
    for name, info in features.items():
        entry = {
            "description": info.get("description", f"Enable {name} support"),
        }
        deps = list(feature_deps.get(name, []))
        for ref in feature_refs.get(name, []):
            ref_plat = ref.get("platform")
            if not ref_plat:
                ref_info = base_registry.get(ref["name"], {})
                ref_plat = ref_info.get("platform", "")
            item = {"name": port_name, "features": [ref["name"]]}
            if ref_plat:
                item["platform"] = ref_plat
            deps.append(item)
        if deps:
            entry["dependencies"] = _merge_deps(deps)
        feat_defs[name] = entry

    default_features = defaults if defaults else None
    desc_ver = display_ver or version

    json_data = {
        "name": port_name,
        "version": version,
        "port-version": revision,
        "description": [
            f"FFmpeg {desc_ver} build for MSVC (use 'static' feature for static libraries).",
        ],
        "homepage": "https://ffmpeg.org",
        "license": None,
        "dependencies": host_deps,
        "features": feat_defs,
    }
    if default_features:
        json_data["default-features"] = default_features

    (port_dir / "vcpkg.json").write_text(
        json.dumps(json_data, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )


def generate_features_cmake(feat_registry: dict, port_dir: Path,
                            source_name: str = "base"):
    """Generate CMake feature-to-flag mappings."""
    if not feat_registry:
        return

    lines = [
        f"# Auto-generated feature to configure flag mappings from {source_name}.yaml",
        "# DO NOT EDIT — regenerated by ffport",
        "",
    ]
    for name, info in feat_registry.items():
        if not isinstance(info, dict):
            continue
        flag = info.get("flag", "")
        pkgconfig = info.get("pkgconfig", "")
        if not flag and not pkgconfig:
            continue
        if pkgconfig:
            lines.append(f'ffmpeg_feature_core({name} "{flag}" {pkgconfig})')
        else:
            lines.append(f'ffmpeg_feature({name} "{flag}")')

    (port_dir / "features.cmake").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _extract_major(version: str) -> str:
    """Extract major version number from a version string."""
    return version.split(".")[0].split("-")[0]


def _merge_deps(deps: list) -> list:
    """Merge feature-reference entries and deduplicate."""
    seen_strings = set()
    groups = {}
    result = []

    for dep in deps:
        if isinstance(dep, str):
            if dep not in seen_strings:
                seen_strings.add(dep)
                result.append(dep)
        elif isinstance(dep, dict):
            if "features" in dep:
                key = (dep.get("name", ""), dep.get("platform", ""))
                groups.setdefault(key, []).extend(dep["features"])
            else:
                result.append(dep)

    for (name, plat), feats in sorted(groups.items()):
        entry = {"name": name, "features": sorted(set(feats))}
        if plat:
            entry["platform"] = plat
        result.append(entry)

    return result
