export const compDesc: Record<string, string> = {
  amf: 'AMD Advanced Media Framework hardware acceleration',
  aom: 'AV1 video codec (libaom)',
  dav1d: 'AV1 video decoder (dav1d)',
  x264: 'H.264 video encoder (libx264)',
  x265: 'H.265/HEVC video encoder (libx265)',
  vvenc: 'H.266/VVC video encoder (VVenc)',
  svtav1: 'Scalable Video Technology AV1 encoder (SVT-AV1)',
  opus: 'Opus audio codec',
  vorbis: 'Vorbis audio codec',
  mp3lame: 'MP3 audio encoder (LAME)',
  speex: 'Speex audio codec',
  theora: 'Theora video codec',
  vpx: 'VP8/VP9 video codec (libvpx)',
  openh264: 'H.264 codec (OpenH264)',
  openjpeg: 'JPEG 2000 codec (OpenJPEG)',
  jxl: 'JPEG XL image codec (libjxl)',
  webp: 'WebP image codec (libwebp)',
  ass: 'ASS/SSA subtitle rendering (libass)',
  freetype: 'FreeType font rendering',
  fontconfig: 'Font configuration and selection',
  fribidi: 'Unicode bidirectional algorithm',
  harfbuzz: 'Text shaping library (HarfBuzz)',
  iconv: 'Character encoding conversion',
  sdl2: 'Simple DirectMedia Layer 2',
  openssl: 'SSL/TLS cryptography (OpenSSL)',
  srt: 'Secure Reliable Transport (libsrt)',
  ssh: 'SSH protocol (libssh)',
  zmq: 'ZeroMQ messaging library',
  zlib: 'Compression (zlib)',
  bzip2: 'Bzip2 compression',
  lzma: 'LZMA compression (liblzma)',
  snappy: 'Snappy compression',
  soxr: 'SoX audio resampler',
  opengl: 'OpenGL rendering',
  opencl: 'OpenCL parallel computing',
  vulkan: 'Vulkan API hardware acceleration',
  nvcodec: 'NVIDIA Video Codec SDK (NVENC/NVDEC)',
  shaderc: 'Shader compilation library',
  d3d11va: 'Direct3D 11 Video Acceleration',
  d3d12va: 'Direct3D 12 Video Acceleration',
  dxva2: 'DirectX Video Acceleration 2',
  mediafoundation: 'Windows Media Foundation',
  'windows-hw': 'Windows hardware acceleration support',
  w32threads: 'Windows threading',
  bluray: 'Blu-ray disc playback (libbluray)',
  dvdnav: 'DVD navigation (libdvdnav)',
  dvdread: 'DVD reading (libdvdread)',
  gme: 'Game music emulation (libgme)',
  modplug: 'Module music playback (libmodplug)',
  openmpt: 'Tracker music playback (libopenmpt)',
  mysofa: 'SOFA head-related transfer function',
  ilbc: 'Internet Low Bitrate Codec (iLBC)',
  tesseract: 'OCR engine (Tesseract)',
  lensfun: 'Lens correction library',
  xml2: 'XML parsing (libxml2)',
  app: 'FFmpeg application suite (ffmpeg/ffplay/ffprobe)',
  base: 'Core FFmpeg libraries (avutil/swresample/swscale)',
  ffmpeg: 'FFmpeg command-line tool',
  ffplay: 'FFplay media player',
  ffprobe: 'FFprobe multimedia analyzer',
  avcodec: 'Audio/Video codec library (libavcodec)',
  avdevice: 'Input/output device library (libavdevice)',
  avfilter: 'Filter graph library (libavfilter)',
  avformat: 'Container format library (libavformat)',
  swresample: 'Audio resampling library (libswresample)',
  swscale: 'Video scaling/colorspace conversion library (libswscale)',
  all: 'All available features',
  'all-gpl': 'All GPL-licensed features',
  'all-lgpl': 'All LGPL-licensed features',
  gpl: 'GPL-licensed components',
  lgpl: 'LGPL-licensed components',
  'license-gpl': 'GPL license compatibility flag',
  static: 'Statically linked binaries',
}
