# DepPackage.cmake — Version / Dependency registry macros

# ---- Version comparison utilities ----

# version_compare(V1 V2 RESULT): RESULT = -1 if V1 < V2, 0 if equal, 1 if V1 > V2
function(version_compare _v1 _v2 _result)
    if("${_v1}" STREQUAL "${_v2}")
        set(${_result} 0 PARENT_SCOPE)
        return()
    endif()
    string(REPLACE "." ";" _p1 "${_v1}")
    string(REPLACE "." ";" _p2 "${_v2}")
    list(LENGTH _p1 _l1)
    list(LENGTH _p2 _l2)
    if(_l1 LESS _l2)
        math(EXPR _max "${_l2}")
    else()
        math(EXPR _max "${_l1}")
    endif()
    while(_l1 LESS _max)
        list(APPEND _p1 0)
        math(EXPR _l1 "${_l1}+1")
    endwhile()
    while(_l2 LESS _max)
        list(APPEND _p2 0)
        math(EXPR _l2 "${_l2}+1")
    endwhile()
    math(EXPR _last "${_max}-1")
    foreach(_i RANGE 0 ${_last})
        list(GET _p1 ${_i} _a)
        list(GET _p2 ${_i} _b)
        if(_a LESS _b)
            set(${_result} -1 PARENT_SCOPE)
            return()
        elseif(_a GREATER _b)
            set(${_result} 1 PARENT_SCOPE)
            return()
        endif()
    endforeach()
    set(${_result} 0 PARENT_SCOPE)
endfunction()

# version_in_range(VERSION RANGE_SPEC RESULT): range spec like ">=7.0 <8.0"
function(version_in_range _ver _range _result)
    string(STRIP "${_range}" _range)
    string(REGEX REPLACE " +" ";" _constraints "${_range}")
    set(_ok TRUE)
    foreach(_c IN LISTS _constraints)
        string(REGEX MATCH "^([<>=!~]+)(.+)$" _dummy "${_c}")
        set(_op  "${CMAKE_MATCH_1}")
        set(_ref "${CMAKE_MATCH_2}")
        version_compare("${_ver}" "${_ref}" _cmp)
        if(_op STREQUAL ">=")
            if(_cmp LESS 0)
                set(_ok FALSE)
            endif()
        elseif(_op STREQUAL ">")
            if(_cmp LESS 1)
                set(_ok FALSE)
            endif()
        elseif(_op STREQUAL "<=")
            if(_cmp GREATER 0)
                set(_ok FALSE)
            endif()
        elseif(_op STREQUAL "<")
            if(_cmp GREATER -1)
                set(_ok FALSE)
            endif()
        elseif(_op STREQUAL "=")
            if(NOT _cmp EQUAL 0)
                set(_ok FALSE)
            endif()
        endif()
    endforeach()
    set(${_result} ${_ok} PARENT_SCOPE)
endfunction()

# version_satisfies(VERSION CONSTRAINT RESULT): constraint like ">=1.2.0"
function(version_satisfies _ver _con _result)
    version_in_range("${_ver}" "${_con}" _res)
    set(${_result} ${_res} PARENT_SCOPE)
endfunction()

# ---- Dependency package registration ----

# dep_package(NAME name DEFAULT ver BUILD cmake|autotools FFMPEG_FLAG --enable-xxx REQUIRES a;b LICENSE gpl)
macro(dep_package)
    cmake_parse_arguments(PKG "" "NAME;DEFAULT;BUILD" "FFMPEG_FLAG;REQUIRES;LICENSE" ${ARGN})
    set_property(GLOBAL PROPERTY "DEP_${PKG_NAME}_DEFAULT"     "${PKG_DEFAULT}")
    set_property(GLOBAL PROPERTY "DEP_${PKG_NAME}_BUILD"       "${PKG_BUILD}")
    set_property(GLOBAL PROPERTY "DEP_${PKG_NAME}_FFMPEG_FLAG" "${PKG_FFMPEG_FLAG}")
    set_property(GLOBAL PROPERTY "DEP_${PKG_NAME}_REQUIRES"    "${PKG_REQUIRES}")
    set_property(GLOBAL PROPERTY "DEP_${PKG_NAME}_LICENSE"     "${PKG_LICENSE}")
    set_property(GLOBAL APPEND  PROPERTY ALL_DEP_NAMES         "${PKG_NAME}")
endmacro()

# dep_package_version(NAME name VERSION ver URL url URL_TYPE tarball|git PATCHES patch1;patch2)
macro(dep_package_version)
    cmake_parse_arguments(VER "" "NAME;VERSION;URL;URL_TYPE" "PATCHES" ${ARGN})
    if(NOT VER_URL_TYPE)
        set(VER_URL_TYPE "tarball")
    endif()
    string(MAKE_C_IDENTIFIER "${VER_NAME}_${VER_VERSION}" _key)
    set_property(GLOBAL PROPERTY "DEP_${_key}_URL"      ${VER_URL})
    set_property(GLOBAL PROPERTY "DEP_${_key}_URL_TYPE" ${VER_URL_TYPE})
    set_property(GLOBAL PROPERTY "DEP_${_key}_PATCHES"  ${VER_PATCHES})
    set_property(GLOBAL APPEND  PROPERTY "DEP_${VER_NAME}_VERSIONS" ${VER_VERSION})
endmacro()

# ---- FFmpeg version family ----

# ffmpeg_family(NAME name VERSION_RANGE ">=7.0 <8.0"|VERSION_MATCH "^master$"
#               URL_TEMPLATE "..." URL url URL_TYPE git
#               PATCHES p1;p2 CONFIGURE_FLAGS --flag1;--flag2
#               DEPS name>=ver;name2;name3>=ver3)
macro(ffmpeg_family)
    cmake_parse_arguments(FAM "" "NAME;VERSION_RANGE;VERSION_MATCH;URL_TEMPLATE;URL;URL_TYPE"
                          "PATCHES;CONFIGURE_FLAGS;DEPS" ${ARGN})
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_VERSION_RANGE"   "${FAM_VERSION_RANGE}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_VERSION_MATCH"   "${FAM_VERSION_MATCH}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_URL_TEMPLATE"    "${FAM_URL_TEMPLATE}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_URL"             "${FAM_URL}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_URL_TYPE"        "${FAM_URL_TYPE}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_PATCHES"         "${FAM_PATCHES}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_CONFIGURE_FLAGS" "${FAM_CONFIGURE_FLAGS}")
    set_property(GLOBAL PROPERTY "FAM_${FAM_NAME}_DEPS"            "${FAM_DEPS}")
    set_property(GLOBAL APPEND  PROPERTY ALL_FAMILIES              "${FAM_NAME}")
endmacro()
