# Unified MSVC toolchain + build environment
#
# Usage:
#   set(CMAKE_TOOLCHAIN_FILE "cmake/ToolchainMSVC.cmake" CACHE FILEPATH "")
#   project(...)   # ← loads this file
#
# After loading:
#   CMake deps:   CMAKE_C_COMPILER=cl, CMAKE_RC_COMPILER=rc, etc.
#   Autotools deps: ENV{CC}=cl, ENV{CFLAGS}=/MD, etc. (inherited by ExternalProject)
if(POLICY CMP0091)
    cmake_policy(SET CMP0091 NEW)
endif()
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreaded CACHE STRING "" FORCE)
set(CMAKE_SYSTEM_NAME       Windows)

# ---- Derive processor and assembler from VS environment ----
if("$ENV{VSCMD_ARG_TGT_ARCH}" STREQUAL "x64")
    set(CMAKE_SYSTEM_PROCESSOR   amd64)
    set(CMAKE_ASM_MASM_COMPILER  nasm     CACHE STRING "" FORCE)
    set(CMAKE_ASM_COMPILER       nasm     CACHE STRING "" FORCE)
elseif("$ENV{VSCMD_ARG_TGT_ARCH}" STREQUAL "x86")
    set(CMAKE_SYSTEM_PROCESSOR   x86)
    set(CMAKE_ASM_MASM_COMPILER  nasm       CACHE STRING "" FORCE)
    set(CMAKE_ASM_COMPILER       nasm       CACHE STRING "" FORCE)
elseif("$ENV{VSCMD_ARG_TGT_ARCH}" STREQUAL "arm")
    set(CMAKE_SYSTEM_PROCESSOR   arm)
    set(CMAKE_ASM_COMPILER       armasm   CACHE STRING "" FORCE)
elseif("$ENV{VSCMD_ARG_TGT_ARCH}" STREQUAL "arm64")
    set(CMAKE_SYSTEM_PROCESSOR   aarch64)
    set(CMAKE_ASM_COMPILER       armasm64 CACHE STRING "" FORCE)
else()
    set(CMAKE_SYSTEM_PROCESSOR   amd64)
    set(CMAKE_ASM_MASM_COMPILER  nasm     CACHE STRING "" FORCE)
    set(CMAKE_ASM_COMPILER       nasm     CACHE STRING "" FORCE)
endif()

# ---- CMake compiler tools (MSVC) ----
set(CMAKE_C_COMPILER    cl   CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER  cl   CACHE STRING "" FORCE)
set(CMAKE_RC_COMPILER   rc   CACHE STRING "" FORCE)
set(CMAKE_AR            lib  CACHE STRING "" FORCE)
set(CMAKE_LINKER        link CACHE STRING "" FORCE)
set(CMAKE_MT            mt   CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -utf-8 -O2 -Z7")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O2 -Z7 -EHsc -utf-8")
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -DEBUG -OPT:REF -OPT:ICF")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS}  -DEBUG -OPT:REF -OPT:ICF")
set(CMAKE_BUILD_TYPE "RelWithDebInfo" CACHE STRING "" FORCE)

set(CMAKE_C_FLAGS_RELWITHDEBINFO   "/MT /O2 /Ob2 /DNDEBUG /Z7" CACHE STRING "" FORCE)
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/MT /O2 /Ob2 /DNDEBUG /Z7" CACHE STRING "" FORCE)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER CACHE STRING "" FORCE)
set(CMAKE_SYSROOT "${STAGE_DIR}" CACHE STRING "" FORCE)
set(CMAKE_FIND_ROOT_PATH "${STAGE_DIR}" CACHE STRING "" FORCE)
set(CMAKE_PKG_CONFIG_PC_PATH "${CMAKE_PKG_CONFIG_PC_PATH}" CACHE STRING "" FORCE)
set(CMAKE_PKG_CONFIG_PC_LIB_DIRS "${CMAKE_PKG_CONFIG_PC_PATH}" CACHE STRING "" FORCE)

string(APPEND CMAKE_C_FLAGS_INIT   " /MP")
string(APPEND CMAKE_CXX_FLAGS_INIT " /MP")

execute_process(
    COMMAND cygpath -u "${STAGE_DIR}"
    OUTPUT_VARIABLE STAGE_DIR_UNIX
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

set(CMAKE_PKG_CONFIG_PC_PATH  "${STAGE_DIR_UNIX}/lib/pkgconfig:${STAGE_DIR_UNIX}/share/pkgconfig"   CACHE STRING "" FORCE)
set(CMAKE_PKG_CONFIG_PC_WIN_PATH  "${STAGE_DIR}/lib/pkgconfig;${STAGE_DIR}/share/pkgconfig"   CACHE STRING "" FORCE)

set(DEPS_CMAKE_ARGS 
    "-DCMAKE_TOOLCHAIN_FILE:FILEPATH=${CMAKE_TOOLCHAIN_FILE}"
    "-DCMAKE_INSTALL_PREFIX=${STAGE_DIR}"
    "-DCMAKE_PREFIX_PATH=${STAGE_DIR}"
    "-DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}"
    "-DCMAKE_POLICY_DEFAULT_CMP0091=NEW"
    "-DCMAKE_POLICY_VERSION_MINIMUM=3.5"
    "-DCMAKE_MSVC_RUNTIME_LIBRARY=${CMAKE_MSVC_RUNTIME_LIBRARY}"
    "-DBUILD_SHARED_LIBS=OFF"
    "-DCMAKE_PKG_CONFIG_PC_PATH=${CMAKE_PKG_CONFIG_PC_WIN_PATH}"
    "-DCMAKE_PKG_CONFIG_PC_LIB_DIRS=${CMAKE_PKG_CONFIG_PC_WIN_PATH}"
    "-DCMAKE_SYSROOT=${STAGE_DIR}"
    "-DCMAKE_FIND_ROOT_PATH=${STAGE_DIR}"
    "-DCMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}"
    "-DCMAKE_ASM_MASM_COMPILER=${CMAKE_ASM_MASM_COMPILER}"
    "-DCMAKE_ASM_COMPILER=${CMAKE_ASM_COMPILER}"
    -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY
    -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
    -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER
)
# ---- Environment variables (inherited by autotools ExternalProject deps) ----

 
set(ENV{CC}              ${CMAKE_C_COMPILER})
set(ENV{CXX}             ${CMAKE_CXX_COMPILER})
set(ENV{RC}              ${CMAKE_RC_COMPILER})
set(ENV{LINKER}          ${CMAKE_LINKER})
set(ENV{LD}              ${CMAKE_LINKER})
set(ENV{MT}              ${CMAKE_MT})
set(ENV{AR}              ${CMAKE_AR})
set(ENV{AS}              ${CMAKE_ASM_COMPILER})
set(ENV{CFLAGS}         "${CMAKE_C_FLAGS}")
set(ENV{LDFLAGS}         "${CMAKE_LD_FLAGS_INIT}")
set(ENV{PKG_CONFIG_PATH} "${CMAKE_PKG_CONFIG_PC_WIN_PATH}")
set(ENV{PKG_CONFIG_LIBDIR} "${CMAKE_PKG_CONFIG_PC_WIN_PATH}")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${STAGE_DIR_UNIX}")
# set(ENV{MSYSTEM_PREFIX} "${STAGE_DIR_UNIX}")
set(ENV{MSYS2_PATH_TYPE} inherit)
set(ENV{MSYS2_ARG_CONV_EXCL} "*")
set(ENV{VSLANG} 1033)
# set(ENV{LC_ALL} C)

set(GENERIC_ENV
    "CC=${CMAKE_C_COMPILER}"
    "CXX=${CMAKE_CXX_COMPILER}"
    "RC=${CMAKE_RC_COMPILER}"
    "LINKER=${CMAKE_LINKER}"
    "LD=${CMAKE_LINKER}"
    "MT=${CMAKE_MT}"
    "AR=${CMAKE_AR}"
    "AS=${CMAKE_ASM_COMPILER}"
    "CFLAGS=${CMAKE_C_FLAGS_INIT}"
    "RANLIB=echo"
    "PKG_CONFIG_PATH=${CMAKE_PKG_CONFIG_PC_PATH}"
    "PKG_CONFIG_LIBDIR=${CMAKE_PKG_CONFIG_PC_PATH}"
    "PKG_CONFIG_SYSROOT_DIR=${STAGE_DIR_UNIX}"
    "MSYS2_PATH_TYPE=inherit"
    "MSYS2_ARG_CONV_EXCL=*"
    "VSLANG=1033"
    "LC_ALL=C"
)

set(COMPAT_ENV 
    ${GENERIC_ENV}
    "CC=${CMAKE_CURRENT_LIST_DIR}/compile-cl"
    "CXX=${CMAKE_CURRENT_LIST_DIR}/compile-cl" 
    "AR=${CMAKE_CURRENT_LIST_DIR}/compile-lib"
    "CFLAGS=$ENV{CFLAGS} -I${STAGE_DIR}/include"
    "LDFLAGS=$ENV{LDFLAGS} -L${STAGE_DIR}/lib"
)
set(SHELL_ENV
    env
    ${GENERIC_ENV}
)
set(SHELL_COMPAT_ENV
    env
    ${COMPAT_ENV}
)